### ISSUE TITLE
Scrollable button identifier number cuts off on top

### ISSUE THREAD

**Issue by DivTheDev** [coval-solutions/height-slider#1]
The height number that identifies the scrollable button cuts off from top edge.

**Comment by DiogoTheCoder** [comment]
Hi @divyesh26 👋,

Thanks for bringing this to our attention. We have committed changes which will solve this issue (https://github.com/coval-solutions/height-slider/commit/0ec0ce5692141a0c8531f6346a89212067b6b437), and the package on http://pub.dev has also been updated (https://pub.dev/packages/height_slider/versions/1.1.1).

Cheers,

@DiogoTheCoder
