### ISSUE TITLE
null-safety upgrade?

### ISSUE THREAD

**Issue by aconitine** [coval-solutions/height-slider#11]
Hi there!
I love your packages height slider and weight slider and I have a project using them. 
Now I think I need to migrate to flutter 2.0 soon.
So I wanna ask your packages to migrate to null-safety also please.

Thanks a lot!

**Comment by DiogoTheCoder** [comment]
Hey @aconitine, will add that to the to-do list definitely.

Will keep you updated :)

Cheers.

**Comment by DiogoTheCoder** [comment]
@aconitine we have gone ahead and upgrade our package to use null safety: https://github.com/coval-solutions/height-slider/releases/tag/1.4.0-nullsafety.

https://pub.dev/packages/height_slider/versions/1.4.0-nullsafety+1.

Cheers.
